name: gtgh2306-exercices
services:
  apache:
    image: httpd
    container_name: gtgh2306-exercices-web
    restart: always
    volumes:
      - './www:/usr/local/apache2/htdocs'
    ports:
      - '3000:80'